'use client'
import type { Metadata } from "next";
import { Inter, Press_Start_2P } from "next/font/google";
import "./globals.css";
import { AptosWalletProvider } from '@razorlabs/wallet-kit';
import '@razorlabs/wallet-kit/style.css';
import ClientLayout from "./ClientLayout";

const inter = Inter({ subsets: ["latin"] });
const bit = Press_Start_2P({subsets:["latin"], weight:["400"]})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClientLayout>
      <body className={inter.className}>{children}</body>
      </ClientLayout>

    </html>
  );
}
